[package]
name = "asset-fingerprint-remover"
version = "0.1.0"
authors = ["Tim Hoiberg <tim.hoiberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
regex = "1.4.2"
